# Generated by Django 2.2.3 on 2019-09-12 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nid', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('contact', models.CharField(blank=True, max_length=60)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(blank=True, max_length=150)),
                ('address3', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(choices=[('CO', 'Colombia'), ('VE', 'Venezuela')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True)),
                ('allowed_users', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('activation_code', models.CharField(default=None, max_length=150, null=True)),
                ('activation_date', models.DateTimeField(default=None, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MessageSet',
            fields=[
                ('message_set', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['message_set'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WebConsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'DEMO'), ('C', 'Contact')], max_length=1)),
                ('name', models.CharField(max_length=60)),
                ('company', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('describe', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_consult',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_license', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.License')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.AddField(
            model_name='license',
            name='modules',
            field=models.ManyToManyField(to='api.Module'),
        ),
        migrations.CreateModel(
            name='MessageCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_nbr', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('message_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.MessageSet')),
            ],
            options={
                'ordering': ['message_set', 'message_nbr'],
                'unique_together': {('message_set', 'message_nbr')},
            },
        ),
    ]
