# Generated by Django 2.2.3 on 2019-07-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'DEMO'), ('C', 'Contact')], max_length=1)),
                ('name', models.CharField(max_length=60)),
                ('company', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('describe', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_consult',
                'ordering': ['-create_date'],
            },
        ),
    ]
