# Generated by Django 2.2.3 on 2019-09-04 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSet',
            fields=[
                ('message_set', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'message_set',
                'ordering': ['message_set'],
            },
        ),
        migrations.CreateModel(
            name='WebConsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'DEMO'), ('C', 'Contact')], max_length=1)),
                ('name', models.CharField(max_length=60)),
                ('company', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('describe', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_consult',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='MessageCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_nbr', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('message_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.MessageSet')),
            ],
            options={
                'db_table': 'message_catalog',
                'ordering': ['message_set', 'message_nbr'],
            },
        ),
    ]
