# Generated by Django 2.2.3 on 2019-09-25 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='license',
            name='activation_code',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='activation_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='allowed_users',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='modules',
            field=models.ManyToManyField(blank=True, to='api.Module'),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
