# Generated by Django 2.2.3 on 2019-09-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='activation_code',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='activation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
