# Generated by Django 2.2.3 on 2019-09-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagecatalog',
            unique_together={('message_set', 'message_nbr')},
        ),
    ]
