# Generated by Django 2.2.3 on 2019-09-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190909_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='license',
            name='allowed_users',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
