# Generated by Django 2.2.3 on 2019-09-26 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('XML', 'XML'), ('TXT', 'TXT'), ('CSV', 'CSV')], default='TXT', max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FileTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('XMLTOTEXT', 'XML a texto plano')], max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('files_in', models.ManyToManyField(related_name='files_in', to='api.File')),
                ('files_out', models.ManyToManyField(blank=True, related_name='files_out', to='api.File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
