# Generated by Django 2.2.3 on 2019-09-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190909_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
