# Generated by Django 2.2.3 on 2019-09-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
